import { UserProvider } from '@auth0/nextjs-auth0/client';
import {Providers} from "./providers";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <UserProvider>
          <Providers>
              <body
                className="dark text-foreground bg-background antialiased"
              >
                {children}
              </body>
           
          </Providers>
      </UserProvider>
    </html>
  );
}
